/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpecIndexRouteImport } from './routes/spec/index'
import { Route as SpecSplatRouteImport } from './routes/spec/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecIndexRoute = SpecIndexRouteImport.update({
  id: '/spec/',
  path: '/spec/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecSplatRoute = SpecSplatRouteImport.update({
  id: '/spec/$',
  path: '/spec/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/spec/$': typeof SpecSplatRoute
  '/spec/': typeof SpecIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/spec/$': typeof SpecSplatRoute
  '/spec': typeof SpecIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/spec/$': typeof SpecSplatRoute
  '/spec/': typeof SpecIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/spec/$' | '/spec/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/spec/$' | '/spec'
  id: '__root__' | '/' | '/spec/$' | '/spec/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SpecSplatRoute: typeof SpecSplatRoute
  SpecIndexRoute: typeof SpecIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spec/': {
      id: '/spec/'
      path: '/spec'
      fullPath: '/spec/'
      preLoaderRoute: typeof SpecIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spec/$': {
      id: '/spec/$'
      path: '/spec/$'
      fullPath: '/spec/$'
      preLoaderRoute: typeof SpecSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SpecSplatRoute: SpecSplatRoute,
  SpecIndexRoute: SpecIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
